#!/usr/bin/env bash

# ensure that multiple, simultaneous IOCs are not started by this user ID

MY_UID=`id -u`
IOC_PID="`/usr/bin/pgrep tucsenApp\$ -u ${MY_UID}`"
export EPICS_CA_AUTO_ADDR_LIST=NO
export EPICS_CA_ADDR_LIST="10.0.0.20 10.0.0.20:8164 10.0.0.20:8166 10.0.0.20:8168 10.0.0.20:8170"
export EPICS_CAS_INTF_ADDR_LIST="localhost ultima1 10.0.0.20 10.0.0.0 10.0.0.1 10.0.0.255"
export EPICS_CA_SERVER_PORT=8168
export EPICS_CA_MAX_ARRAY_BYTES=75000000

if [ "" != "${IOC_PID}" ] ; then
  echo "tucsen IOC is already running, won't start a new one, PID=${IOC_PID}"
  exit 1
fi

# start the IOC
/opt/epics/sigApps/ioc/tucsen/iocs/tucsenIOC/bin/linux-x86_64/tucsenApp /opt/epics/sigApps/ioc/tucsen/iocs/tucsenIOC/iocBoot/iocTucsen/st.cmd
